# Generated by Django 3.1.7 on 2022-02-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Card_Model',
        ),
    ]
