# Generated by Django 3.1.7 on 2022-02-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_card_model_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_model',
            old_name='role',
            new_name='job_role',
        ),
    ]
