# Generated by Django 3.1.7 on 2022-02-10 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_card_model_apply_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_model',
            name='job_title',
        ),
        migrations.AddField(
            model_name='card_model',
            name='batch',
            field=models.CharField(blank=True,  max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_model',
            name='degree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card_model',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card_model',
            name='salary',
            field=models.CharField(blank=True, default="N/A", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card_model',
            name='last_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
