# Generated by Django 3.1.7 on 2022-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20220210_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
