# Generated by Django 3.1.7 on 2022-02-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20220210_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_model',
            name='job_role',
        ),
    ]
