# Generated by Django 3.1.7 on 2022-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20220210_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='batch',
            field=models.CharField(blank=True, default='Any Batch', max_length=50),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='degree',
            field=models.CharField(blank=True, default='Not Disclosed', max_length=50),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='last_date',
            field=models.DateField(blank=True, default='Not Disclosed'),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='location',
            field=models.CharField(blank=True, default='PAN India', max_length=50),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='salary',
            field=models.IntegerField(blank=True, default='Not Disclosed', max_length=50),
        ),
    ]
