# Generated by Django 3.1.7 on 2022-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20220210_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='last_date',
            field=models.CharField(blank=True, default='Not Disclosed', max_length=50),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='salary',
            field=models.CharField(blank=True, default='Not Disclosed', max_length=50),
        ),
    ]
