# Generated by Django 3.1.7 on 2022-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20220210_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('Skill_des', models.TextField()),
                ('min_qulification', models.TextField()),
                ('how_to_apply', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card_model',
            name='apply_link',
        ),
    ]
