# Generated by Django 4.0.2 on 2022-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20220210_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_model',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
