# Generated by Django 4.0.2 on 2022-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_card_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
