# Generated by Django 3.1.7 on 2022-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20220213_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card_model',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
