# Generated by Django 3.1.7 on 2022-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_auto_20220213_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='card_model',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
