# Generated by Django 4.0.2 on 2022-02-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_alter_card_model_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_model',
            name='apply_link',
        ),
    ]
