# Generated by Django 3.1.7 on 2022-02-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_auto_20220213_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='Skill_des',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='how_to_apply',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='min_qulification',
        ),
    ]
