# Generated by Django 4.0.2 on 2022-02-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_blog_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_model',
            old_name='des',
            new_name='content',
        ),
    ]
