# Generated by Django 4.0.2 on 2022-02-12 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_rename_des_blog_model_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
