# Generated by Django 4.0.2 on 2022-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_blog_model_skill_des_blog_model_how_to_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
