# Generated by Django 4.0.2 on 2022-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_blog_model_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
