# Generated by Django 4.0.2 on 2022-02-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_blog_model_views'),
        ('homeapp', '0014_contactmodel'),
    ]

    operations = [
    ]
