# Generated by Django 4.0.2 on 2022-02-12 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_blog_model_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_model',
            old_name='content',
            new_name='Skill_des',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_model',
            name='how_to_apply',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_model',
            name='min_qulification',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
