# Generated by Django 4.0.2 on 2022-02-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_rename_content_blog_model_skill_des_blog_model_des_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='Skill_des',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='how_to_apply',
        ),
        migrations.RemoveField(
            model_name='blog_model',
            name='min_qulification',
        ),
    ]
