# Generated by Django 4.0.2 on 2022-02-12 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_remove_blog_model_skill_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='Skill_des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_model',
            name='how_to_apply',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_model',
            name='min_qulification',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
