# Generated by Django 4.0.2 on 2022-02-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_rename_des_blog_model_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_model',
            old_name='content',
            new_name='des',
        ),
    ]
