# Generated by Django 4.0.2 on 2022-02-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0019_rename_content_blog_model_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_model',
            old_name='des',
            new_name='content',
        ),
    ]
